# Instance variables
vm-zone             = "me-central2-b"
vm-name             = "senai-dev-vm"
machine_type        = "e2-standard-2"
device_name         = "senai-dev"
image               = "projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20250111"
size                = "50"
type                = "pd-ssd"
disk_label          = "senai-terraform-disk-dev"
can_ip_forward      = "false"
deletion_protection = "false"
assign_external_ip  = "false"
network_tier        = "STANDARD"
#static_ip_address   = "34.166.93.118"
vm-tags = {
  "tag1" = "http-server",
  "tag2" = "https-server",
  "tag3" = "lb-health-check",
  "tag4" = "port81"
}
# SQL variables
db-instance-name               = "senai-dev"
db-name                        = "senai-database-dev"
database_version               = "MYSQL_8_4"
db-region                      = "me-central2"
db-user                        = "dev-user"
db-password                    = "dev-root"
db-tier                        = "db-n1-standard-1"
db-edition                     = "ENTERPRISE"
db-availability_type           = "ZONAL"
db-disk_autoresize             = "true"
db-disk_size                   = "20"
db-disk_type                   = "PD_SSD"
db-deletion_protection_enabled = "false"
db-private_network             = "https://www.googleapis.com/compute/v1/projects/mim-integrations/global/networks/main"
db-ipv4_enabled                = "false"
db-allocated_ip_range          = ""
db-retained_backups            = "7"
db-retention_unit              = "COUNT"
db-deletion_protection         = "false"
# Bucket variables
bucket-name          = "senai-dev"
bucket-storage_class = "STANDARD"
bucket-force_destroy = "true"
